version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: concierge
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: ../
      dockerfile: packages/api/Dockerfile
    env_file:
      - ../packages/api/.env
    environment:
      DATABASE_URL: postgresql://app:app@db:5432/concierge
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis

  web:
    build:
      context: ../
      dockerfile: packages/web/Dockerfile
    env_file:
      - ../packages/web/.env
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:

