name: catalog-nightly-sync

on:
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Validate secrets
        run: |
          : "${{ secrets.CATALOG_SYNC_URL }}" && : "${{ secrets.CATALOG_SYNC_KEY }}"
      - name: Trigger sync
        run: |
          set -euo pipefail
          curl -sS -X POST "${{ secrets.CATALOG_SYNC_URL }}" \
            -H "X-Catalog-Sync-Key: ${{ secrets.CATALOG_SYNC_KEY }}" \
            -H 'Accept: application/json' \
            -w '\nHTTP %{http_code}\n' -o resp.json
          cat resp.json
          code=$(tail -n1 resp.json | sed -n 's/.*HTTP \([0-9][0-9][0-9]\).*/\1/p')
          [ "$code" = "200" ] || { echo "Non-200: $code"; exit 1; }
