name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render API Deploy
        run: |
          if [ -n "$RENDER_DEPLOY_HOOK_API" ]; then
            echo "Triggering Render deploy"
            curl -fsS -X POST "$RENDER_DEPLOY_HOOK_API"
          else
            echo "RENDER_DEPLOY_HOOK_API not set; skipping"
          fi
        env:
          RENDER_DEPLOY_HOOK_API: ${{ secrets.RENDER_DEPLOY_HOOK_API }}

  # Vercel usually deploys on push via GitHub app. If needed, add CLI deploy here.
